version: "3"
volumes:
  mysql-data: ~
services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    ports:
      - '${MYSQL_PORT}:3306'
    volumes:
      - "mysql-data:/var/lib/mysql"
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - '${ADMINER_PORT}:8080'

  nginx:
    image: nginx:1.19-alpine
    restart: on-failure
    env_file:
      - .env
    volumes:
      - './:/usr/src/project'
      - './resources/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '${NGINX_PORT}:80'
    depends_on:
      - phpfpm

  phpfpm:
    build:
      context: .
      target: base
    env_file:
      - .env
    restart: on-failure
    volumes:
      - './:/usr/src/project'
      - '~/.composer:/root/.config/composer'  # required to install private packages and use your auth.json in the container
      - '~/.ssh:/root/.ssh'                   # required to clone private repositories

  dev:
    build:
      context: .
      target: base
    working_dir: /usr/src/project/apps/ui
    entrypoint: /usr/bin/npm
    command: start
    env_file:
      - .env
    restart: on-failure
    volumes:
      - './:/usr/src/project'
    ports:
      - "3000:3000"

  spritesheet-generator:
    build:
      context: apps/spritesheet-generator
    env_file:
      - .env
    environment:
      - SOURCES_DIR=/usr/shared/sources
      - DIST_DIR=/usr/shared/dist
      - RESOURCES_DIR=/usr/shared/resources
      - SPRITESHEETS_DIR=/usr/shared/ui-public/assets/spritesheets/pokemon
      - HOME_IMG_DIR=/usr/shared/sources/livingdex-renders/images/pokemon
      - POKESPRITE_IMG_DIR=/usr/shared/sources/msikma-pokesprite/pokemon-gen8
      - POKEMON_JSON_FILE=/usr/shared/dist/json/gen/8/pokemon-forms.json
    restart: on-failure
    volumes:
      - './apps/spritesheet-generator:/usr/src/app'
      - './apps/ui/public:/usr/shared/ui-public'
      - './.sources:/usr/shared/sources:ro'
      - './dist:/usr/shared/dist:ro'
      - './resources:/usr/shared/resources:ro'
