version: "3"
services:
  make:
    build:
      context: .
      dockerfile: Dockerfile
      target: make
    command: start
    env_file:
      - .env
    restart: on-failure
    volumes:
      - './:/usr/src/project'
      - '~/.ssh:/root/.ssh' # required to install private packages
    ports:
      - "3000:3000"
