version: "3.8"
services:
  frontend:
    build:
      context: .
      target: dev-frontend
    command: ["npm", "start"]
    restart: on-failure
    environment:
      - DIST_DIR=/usr/src/app/dist
    ports:
      - "3003:3000"
    volumes:
      - "./:/usr/src/app"
