#!/usr/bin/env bash

# IMPORTANT: this script is a dockerized version of ./apps/cli/livingdex
#   use ./apps/cli/livingdex instead when running a command directly inside of a docker container.

if [[ "${1}" == "exec" ]]; then
  docker-compose run --rm phpfpm "${@:2}"
  exit
fi

if [[ "${1}" == "start" ]]; then
  docker-compose up -d
  exit
fi

if [[ "${1}" == "down" ]]; then
  docker-compose down --remove-orphans
  exit
fi

if [[ "${1}" == "recreate" ]]; then
  docker-compose down --remove-orphans
  docker-compose build
  docker-compose up -d
  exit
fi

if [[ "${1}" == "open" ]]; then
  open "http://localhost:${NGINX_PORT}"
  open "http://localhost:${ADMINER_PORT}/?server=mysql&username=test&db=livingdex"
  # open "http://localhost:${NGINX_PORT}/livingdex/"
  open "http://localhost:3000"
fi

docker-compose run --rm --workdir=/usr/src/project --entrypoint=/usr/src/project/apps/cli/livingdex phpfpm "${@}"
