name: Docker Image CI

on:
  push:
    # Run on push of any of these branches
    branches:
      - main

    # Run on every new semver tag
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:

  publish-docker-image:

    runs-on: ubuntu-latest

    steps:      
    - uses: actions/checkout@v2

    - id: get_version
      name: Split semver tag
      uses: battila7/get-version-action@v2

    - name: Set env variables
      run: |
          echo "DOCKER_IMAGE_URI=docker.pkg.github.com/itsjavi/livingdex-data/livingdex-data" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_TAG_IS_SEMVER=${{ steps.get_version.outputs.is_semver }}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_TAG_MAJOR=${{ steps.get_version.outputs.major }}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_TAG_MINOR=${{ steps.get_version.outputs.major }}.${{ steps.get_version.outputs.minor }}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE_TAG_PATCH=${{ steps.get_version.outputs.version }}" >> $GITHUB_ENV

      
    - name: Print env variables
      run: |
          echo "Home: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "DOCKER_IMAGE_URI: ${DOCKER_IMAGE_URI}"
          echo "DOCKER_IMAGE_TAG_IS_SEMVER: ${DOCKER_IMAGE_TAG_IS_SEMVER}"
          echo "DOCKER_IMAGE_TAG_MAJOR: ${DOCKER_IMAGE_TAG_MAJOR}"
          echo "DOCKER_IMAGE_TAG_MINOR: ${DOCKER_IMAGE_TAG_MINOR}"
          echo "DOCKER_IMAGE_TAG_PATCH: ${DOCKER_IMAGE_TAG_PATCH}"
    
    - name: Build and Push the Docker image
      run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u itsjavi --password-stdin

          echo "DOCKER_IMAGE_TAG_IS_SEMVER: ${DOCKER_IMAGE_TAG_IS_SEMVER}"
          echo "DOCKER_IMAGE_TAG_MAJOR: ${DOCKER_IMAGE_TAG_MAJOR}"
          echo "DOCKER_IMAGE_TAG_MINOR: ${DOCKER_IMAGE_TAG_MINOR}"
          echo "DOCKER_IMAGE_TAG_PATCH: ${DOCKER_IMAGE_TAG_PATCH}"

          ls -la

          docker build -t "${DOCKER_IMAGE_URI}:latest" --target=builder-with-source .

          if [ -n "${DOCKER_IMAGE_TAG_MAJOR}" ]; then
            echo "Creating SEMVER docker tags (${DOCKER_IMAGE_TAG_PATCH}) ..."

            docker tag "${DOCKER_IMAGE_URI}:latest" "${DOCKER_IMAGE_URI}:${DOCKER_IMAGE_TAG_MAJOR}"
            docker tag "${DOCKER_IMAGE_URI}:latest" "${DOCKER_IMAGE_URI}:${DOCKER_IMAGE_TAG_MINOR}"
            docker tag "${DOCKER_IMAGE_URI}:latest" "${DOCKER_IMAGE_URI}:${DOCKER_IMAGE_TAG_PATCH}"
          else
            echo "Creating NOT-SEMVER docker tags (main) ..."

            docker tag "${DOCKER_IMAGE_URI}:latest" "${DOCKER_IMAGE_URI}:main"
          fi
          
          docker image push --all-tags ${DOCKER_IMAGE_URI}
