# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    export_empty_values: false
    export_format: json
    build_dir: '%kernel.project_dir%/var/build'
    assets_dir: '%kernel.project_dir%/public/assets'
    sources_dir: '%env(string:SOURCES_DIR)%'
    showdown_data_dir: '%sources_dir%/showdown-data/dist/data'
    pokesprite_dir: '%sources_dir%/msikma-pokesprite'
    home_images_dir: '%sources_dir%/livingdex-renders/images/home'
    data_extras_dir: '%kernel.project_dir%/data'
    csv_data_dir: '%env(string:DIST_DIR)%/csv'
    json_data_dir: '%env(string:DIST_DIR)%/json'
    veekun_db_file: '%kernel.project_dir%/var/data/veekun-pokedex.sqlite'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $defaultConnection : '@doctrine.dbal.default_connection'
            $veekunConnection : '@doctrine.dbal.veekun_connection'
            $showdownDataDir: '%showdown_data_dir%'
            $pokespriteDir: '%pokesprite_dir%'
            $homeImagesDir: '%home_images_dir%'
            $dataExtrasDir: '%data_extras_dir%'
            $csvDataDir: '%csv_data_dir%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Scripts/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
