doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                url: '%env(resolve:DATABASE_URL)%'
                charset: utf8mb4
                logging: false
                profiling: false
            veekun:
                url: 'sqlite:///%veekun_db_file%'
                charset: utf8mb4
                logging: false
                profiling: false
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Main:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/LivingDex'
                        prefix: 'App\Entity\LivingDex'
                        alias: LivingDex
#            veekun:
#                connection: veekun
#                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
#                mappings:
#                    Customer:
#                        is_bundle: false
#                        type: annotation
#                        dir: '%kernel.project_dir%/src/Entity/Veekun'
#                        prefix: 'App\Entity\Veekun'
#                        alias: Veekun
