version: "3"
volumes:
    mysql-data: ~
services:
    mysql:
        image: mysql:8.0
        restart: on-failure
        command:
            - '--character-set-server=utf8mb4'
            - '--collation-server=utf8mb4_unicode_ci'
        ports:
            - '${MYSQL_PORT}:3306'
        volumes:
            - "mysql-data:/var/lib/mysql"
        environment:
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}

    adminer:
        image: adminer
        restart: on-failure
        ports:
            - '${ADMINER_PORT}:8080'

    nginx:
        image: nginx:1.19-alpine
        restart: on-failure
        volumes:
            - './public:/usr/src/app'
            - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
        ports:
            - '${NGINX_PORT}:80'
        depends_on:
            - phpfpm

    phpfpm:
        build:
            context: .
            target: base
        restart: on-failure
        volumes:
            - './:/usr/src/app'
            - '~/.composer:/root/.config/composer'  # required to install private packages and use your auth.json in the container
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
            - APP_DEBUG=1
            - COMPOSER_ALLOW_SUPERUSER=1
            - COMPOSER_PROCESS_TIMEOUT=0
            - COMPOSER_MEMORY_LIMIT=3G
            - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@mysql:3306/${DATABASE_NAME}?serverVersion=8.0
